### ISSUE TITLE
updating my posted library?

### ISSUE THREAD

**Issue by vipulasri** [liaohuqiu/android-gems-web#3]
There is no way to update my posted Library.

**Comment by liaohuqiu** [comment]
Which part information you want to update?

**Comment by vipulasri** [comment]
i want to update demo in my library badge view.

http://www.android-gems.com/lib/vipulasri/Timeline-View?lib_id=773

**Comment by liaohuqiu** [comment]
I've updated that you. I think I will be better to update automatically once you pushed your code.

**Comment by vipulasri** [comment]
@liaohuqiu I think then you should build the feature edit/update for changes.

**Comment by liaohuqiu** [comment]
Yep, thank you. Now we can edit description and snapshots, but the `apk` is built by the build system. I will make the build process automatically.

**Comment by vipulasri** [comment]
Great @liaohuqiu
