### ISSUE TITLE
OAuth Permissions

### ISSUE THREAD

**Issue by hgross** [liaohuqiu/android-gems-web#5]
Hi,

I wanted to submit https://github.com/Blaubot/Blaubot but giving android-gems that much permissions is simply not acceptable:

![list of permissions](http://abload.de/img/unspecifiedmus9o.png)

Is there any reason for that?

cheers

**Comment by liaohuqiu** [comment]
Sorry, that's too much. I will remove the unnecessary ASAP. Thank you.
